### ISSUE TITLE
Battery sourcing?

### ISSUE THREAD

**Issue by MatthewEdge** [GEIGEIGEIST/TOTEM#23]
Less an issue and more a question as I couldn't find it in the build guide or the written post: where did you end up sourcing your batteries for the wireless version from? 👀 I've been having quite the difficulty finding a battery that fits!

Cheers for a fantastic project overall!

**Comment by spamwax** [comment]
this should fit:
https://www.aliexpress.us/item/2251832763323258.html

**Comment by MatthewEdge** [comment]
Thank you!

**Comment by janthmueller** [comment]
If you get a 404 because the product isn’t available in your region, you might need a VPN to view it. I fetched the product title:

5 pcs 3.7V 100mAh Li-po Battery for Hubsan Q4 Wltoys V272 Mini RC Quadcopter Drone Battery

If you search on AliExpress, you will most likely find a product that can be shipped to your region.
