### ISSUE TITLE
Can a different reset button between used? 

### ISSUE THREAD

**Issue by that-ambuj** [GEIGEIGEIST/TOTEM#37]
The Alps reset mentioned in the buildguide is not available in my country. Can I use something else like this: https://amzn.in/d/hXtKUwA ?

**Comment by Kcebnelloh** [comment]
The footprint of the part needs to match so that you can solder it into the pcb correctly. Also if you want to use the case, then it has to be exactly the same part. I found them here on aliexpress: https://de.aliexpress.com/item/1005005594042307.html?spm=a2g0o.order_list.order_list_main.82.5f1f5c5f0dZXGI&gatewayAdapt=glo2deu

**Comment by that-ambuj** [comment]
Unfortunately, Aliexpress is not available in my country otherwise this would've been a whole lot easier.
